<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HomeServicePlatform.Application\HomeServicePlatform.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Persistence\Repositories\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
