// <auto-generated />
using System;
using HomeServicePlatform.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeServicePlatform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260715183512_AddServiceImageUrl")]
    partial class AddServiceImageUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Bookings.Entities.Booking", b =>
                {
                    b.Property<long>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("booking_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BookingId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<decimal?>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("discount_amount");

                    b.Property<DateTimeOffset?>("EmergencyExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("emergency_expires_at");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("final_amount");

                    b.Property<bool>("IsEmergency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_emergency");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("row_version");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("status");

                    b.Property<decimal>("SubtotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal_amount");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("BookingId");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_bookings_status");

                    b.HasIndex("CustomerId", "CreatedAt")
                        .HasDatabaseName("ix_bookings_customer_created");

                    b.ToTable("bookings", null, t =>
                        {
                            t.HasCheckConstraint("ck_bookings_amount", "subtotal_amount >= 0 AND discount_amount >= 0 AND final_amount >= 0");
                        });
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Bookings.Entities.BookingAddress", b =>
                {
                    b.Property<long>("BookingAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("booking_address_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BookingAddressId"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address_line");

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("booking_id");

                    b.Property<string>("DistrictCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("district_code");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<Point>("Geom")
                        .HasColumnType("geometry")
                        .HasColumnName("geom");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("ProvinceCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("province_code");

                    b.Property<string>("WardCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ward_code");

                    b.HasKey("BookingAddressId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("booking_addresses", (string)null);
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Bookings.Entities.BookingItem", b =>
                {
                    b.Property<long>("BookingItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("booking_item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BookingItemId"));

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("booking_id");

                    b.Property<string>("CancelRejectReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancel_reject_reason");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("row_version");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("status");

                    b.Property<long?>("TaskerId")
                        .HasColumnType("bigint")
                        .HasColumnName("tasker_id");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_price");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("BookingItemId");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_booking_items_booking_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_booking_items_service_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_booking_items_status");

                    b.HasIndex("TaskerId", "StartAt", "EndAt")
                        .HasDatabaseName("ix_booking_items_tasker_time");

                    b.ToTable("booking_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_booking_items_duration", "duration_minutes > 0");

                            t.HasCheckConstraint("ck_booking_items_quantity", "quantity > 0");

                            t.HasCheckConstraint("ck_booking_items_time", "start_at < end_at");

                            t.HasCheckConstraint("ck_booking_items_total_price", "total_price >= 0");

                            t.HasCheckConstraint("ck_booking_items_unit_price", "unit_price >= 0");
                        });
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Customer.Entities.Address", b =>
                {
                    b.Property<long>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("address_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AddressId"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address_line");

                    b.Property<string>("DistrictCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("district_code");

                    b.Property<Point>("Geom")
                        .HasColumnType("geometry")
                        .HasColumnName("geom");

                    b.Property<bool?>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("ProvinceCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("province_code");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("WardCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ward_code");

                    b.HasKey("AddressId");

                    b.HasIndex("Geom")
                        .HasDatabaseName("gist_addresses_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "gist");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_addresses_user_id");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Identity.Entities.Role", b =>
                {
                    b.Property<short>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Identity.Entities.Token", b =>
                {
                    b.Property<long>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("token_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TokenId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenString")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId");

                    b.HasIndex("ExpiredAt")
                        .HasDatabaseName("ix_tokens_expired_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tokens_user_id");

                    b.ToTable("tokens", (string)null);
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Identity.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("row_version");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ux_users_phone")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_users_status");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_status", "status IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Identity.Entities.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Operations.Entities.BookingHistory", b =>
                {
                    b.Property<long>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("history_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("HistoryId"));

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("booking_id");

                    b.Property<long?>("ChangedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("changed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<short?>("NewStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("new_status");

                    b.Property<short?>("OldStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("old_status");

                    b.HasKey("HistoryId");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_booking_histories_booking_id");

                    b.HasIndex("ChangedBy");

                    b.ToTable("booking_histories", (string)null);
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Operations.Entities.Commission", b =>
                {
                    b.Property<long>("CommissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("commission_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CommissionId"));

                    b.Property<decimal>("CommissionRate")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("commission_rate");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<long?>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<long?>("TaskerId")
                        .HasColumnType("bigint")
                        .HasColumnName("tasker_id");

                    b.HasKey("CommissionId");

                    b.HasIndex("TaskerId");

                    b.HasIndex("ServiceId", "TaskerId")
                        .HasDatabaseName("ix_commissions_lookup")
                        .HasFilter("effective_to IS NULL");

                    b.ToTable("commissions", null, t =>
                        {
                            t.HasCheckConstraint("ck_commissions_date", "effective_to IS NULL OR effective_from < effective_to");

                            t.HasCheckConstraint("ck_commissions_rate", "commission_rate BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Operations.Entities.Dispute", b =>
                {
                    b.Property<long>("DisputeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("dispute_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DisputeId"));

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("RaisedById")
                        .HasColumnType("bigint")
                        .HasColumnName("raised_by_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<decimal?>("RefundAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("refund_amount");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text")
                        .HasColumnName("resolution_note");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("row_version");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("DisputeId");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_disputes_booking_id");

                    b.HasIndex("RaisedById");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_disputes_status");

                    b.ToTable("disputes", null, t =>
                        {
                            t.HasCheckConstraint("ck_disputes_refund", "refund_amount >= 0");
                        });
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Operations.Entities.Message", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MessageId"));

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("booking_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint")
                        .HasColumnName("sender_id");

                    b.HasKey("MessageId");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_messages_sender_id");

                    b.HasIndex("BookingId", "CreatedAt")
                        .HasDatabaseName("ix_messages_booking_id_created_at");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Operations.Entities.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("notification_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NotificationId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<int?>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("status");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_notifications_user_status");

                    b.ToTable("notifications", null, t =>
                        {
                            t.HasCheckConstraint("ck_notifications_retry", "retry_count >= 0");
                        });
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Operations.Entities.Review", b =>
                {
                    b.Property<long>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("review_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReviewId"));

                    b.Property<long>("BookingItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("booking_item_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.Property<long>("TaskerId")
                        .HasColumnType("bigint")
                        .HasColumnName("tasker_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ReviewId");

                    b.HasIndex("BookingItemId")
                        .IsUnique();

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_reviews_customer_id");

                    b.HasIndex("Rating")
                        .HasDatabaseName("ix_reviews_rating");

                    b.HasIndex("TaskerId")
                        .HasDatabaseName("ix_reviews_tasker_id");

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasCheckConstraint("ck_reviews_rating", "rating BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Payments.Entities.Payment", b =>
                {
                    b.Property<long>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("payment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<short>("Method")
                        .HasColumnType("smallint")
                        .HasColumnName("method");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("row_version");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("status");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transaction_code");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("PaymentId");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_payments_booking_id");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_payments_amount", "amount >= 0");
                        });
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Payments.Entities.Refund", b =>
                {
                    b.Property<long>("RefundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("refund_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RefundId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<short>("InitiatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("initiated_by");

                    b.Property<long>("PaymentId")
                        .HasColumnType("bigint")
                        .HasColumnName("payment_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<short>("RefundMethod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("refund_method");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status");

                    b.HasKey("RefundId");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_refunds_booking_id");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("ix_refunds_payment_id");

                    b.ToTable("refunds", null, t =>
                        {
                            t.HasCheckConstraint("ck_refunds_amount", "amount >= 0");
                        });
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Payments.Entities.Wallet", b =>
                {
                    b.Property<long>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("wallet_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("WalletId"));

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("balance");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("WalletId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("wallets", (string)null);
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Payments.Entities.WalletTransaction", b =>
                {
                    b.Property<long>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("transaction_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("balance_after");

                    b.Property<decimal>("BalanceBefore")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("balance_before");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("ReferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("reference_id");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<long>("WalletId")
                        .HasColumnType("bigint")
                        .HasColumnName("wallet_id");

                    b.HasKey("TransactionId");

                    b.HasIndex("ReferenceId")
                        .HasDatabaseName("ix_wallet_transactions_ref");

                    b.HasIndex("WalletId", "CreatedAt")
                        .HasDatabaseName("ix_wallet_transactions_wallet_id_created_at");

                    b.ToTable("wallet_transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_wallet_transactions_amount", "amount <> 0");
                        });
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Services.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_url");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Services.Entities.Service", b =>
                {
                    b.Property<long>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ServiceId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ServiceId");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_services_category_id");

                    b.ToTable("services", null, t =>
                        {
                            t.HasCheckConstraint("ck_services_duration", "duration_minutes > 0");
                        });
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Tasker.Entities.TaskerProfile", b =>
                {
                    b.Property<long>("TaskerProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("tasker_profile_id");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("bio");

                    b.Property<int>("CancelCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("cancel_count");

                    b.Property<int>("CompletedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("completed_count");

                    b.Property<Point>("CurrentGeom")
                        .HasColumnType("geometry")
                        .HasColumnName("current_geom");

                    b.Property<int>("ExperienceYears")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("experience_years");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<decimal>("RatingAvg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("rating_avg");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("status");

                    b.Property<int>("TotalReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_reviews");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("TaskerProfileId");

                    b.HasIndex("CurrentGeom")
                        .HasDatabaseName("gist_tasker_current_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CurrentGeom"), "gist");

                    b.HasIndex("IsVerified")
                        .HasDatabaseName("ix_tasker_profile_verified");

                    b.HasIndex("RatingAvg")
                        .HasDatabaseName("ix_tasker_profile_rating");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_tasker_profile_status");

                    b.ToTable("tasker_profile", null, t =>
                        {
                            t.HasCheckConstraint("ck_tasker_profile_experience", "experience_years >= 0");

                            t.HasCheckConstraint("ck_tasker_profile_rating", "rating_avg BETWEEN 0 AND 5");
                        });
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Tasker.Entities.TaskerSchedule", b =>
                {
                    b.Property<long>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("schedule_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ScheduleId"));

                    b.Property<short>("DayOfWeek")
                        .HasColumnType("smallint")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<long>("TaskerId")
                        .HasColumnType("bigint")
                        .HasColumnName("tasker_id");

                    b.HasKey("ScheduleId");

                    b.HasIndex("TaskerId");

                    b.ToTable("tasker_schedules", null, t =>
                        {
                            t.HasCheckConstraint("ck_tasker_schedules_day", "day_of_week BETWEEN 0 AND 6");

                            t.HasCheckConstraint("ck_tasker_schedules_time", "start_time < end_time");
                        });
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Tasker.Entities.TaskerService", b =>
                {
                    b.Property<long>("TaskerId")
                        .HasColumnType("bigint")
                        .HasColumnName("tasker_id");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.HasKey("TaskerId", "ServiceId");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_tasker_services_service_id");

                    b.HasIndex("TaskerId")
                        .HasDatabaseName("ix_tasker_services_tasker_id");

                    b.ToTable("tasker_services", (string)null);
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Tasker.Entities.TaskerServicePrice", b =>
                {
                    b.Property<long>("TaskerServicePriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("tasker_service_price_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TaskerServicePriceId"));

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<long>("TaskerId")
                        .HasColumnType("bigint")
                        .HasColumnName("tasker_id");

                    b.HasKey("TaskerServicePriceId");

                    b.HasIndex("TaskerId");

                    b.HasIndex("ServiceId", "EffectiveFrom", "EffectiveTo")
                        .HasDatabaseName("ix_service_prices_service_id_effective");

                    b.ToTable("tasker_service_prices", null, t =>
                        {
                            t.HasCheckConstraint("ck_service_prices_date", "effective_to IS NULL OR effective_from < effective_to");

                            t.HasCheckConstraint("ck_service_prices_price", "price >= 0");
                        });
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Tasker.Entities.TaskerTimeOff", b =>
                {
                    b.Property<long>("TimeOffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("time_off_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TimeOffId"));

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<long>("TaskerId")
                        .HasColumnType("bigint")
                        .HasColumnName("tasker_id");

                    b.HasKey("TimeOffId");

                    b.HasIndex("TaskerId");

                    b.ToTable("tasker_time_offs", null, t =>
                        {
                            t.HasCheckConstraint("ck_tasker_time_offs_time", "start_at < end_at");
                        });
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Bookings.Entities.Booking", b =>
                {
                    b.HasOne("HomeServicePlatform.Domain.Modules.Identity.Entities.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_customer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Bookings.Entities.BookingAddress", b =>
                {
                    b.HasOne("HomeServicePlatform.Domain.Modules.Bookings.Entities.Booking", "Booking")
                        .WithOne("BookingAddress")
                        .HasForeignKey("HomeServicePlatform.Domain.Modules.Bookings.Entities.BookingAddress", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_addresses_booking");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Bookings.Entities.BookingItem", b =>
                {
                    b.HasOne("HomeServicePlatform.Domain.Modules.Bookings.Entities.Booking", "Booking")
                        .WithMany("BookingItems")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_items_booking");

                    b.HasOne("HomeServicePlatform.Domain.Modules.Services.Entities.Service", "Service")
                        .WithMany("BookingItems")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_items_service");

                    b.HasOne("HomeServicePlatform.Domain.Modules.Tasker.Entities.TaskerProfile", "TaskerProfile")
                        .WithMany()
                        .HasForeignKey("TaskerId")
                        .HasConstraintName("fk_booking_items_tasker_profile");

                    b.Navigation("Booking");

                    b.Navigation("Service");

                    b.Navigation("TaskerProfile");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Customer.Entities.Address", b =>
                {
                    b.HasOne("HomeServicePlatform.Domain.Modules.Identity.Entities.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_addresses_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Identity.Entities.Token", b =>
                {
                    b.HasOne("HomeServicePlatform.Domain.Modules.Identity.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tokens_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Identity.Entities.UserRole", b =>
                {
                    b.HasOne("HomeServicePlatform.Domain.Modules.Identity.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_role");

                    b.HasOne("HomeServicePlatform.Domain.Modules.Identity.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_user");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Operations.Entities.BookingHistory", b =>
                {
                    b.HasOne("HomeServicePlatform.Domain.Modules.Bookings.Entities.Booking", "Booking")
                        .WithMany("BookingHistories")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_histories_booking");

                    b.HasOne("HomeServicePlatform.Domain.Modules.Identity.Entities.User", "Changer")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .HasConstraintName("fk_booking_histories_changed_by");

                    b.Navigation("Booking");

                    b.Navigation("Changer");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Operations.Entities.Commission", b =>
                {
                    b.HasOne("HomeServicePlatform.Domain.Modules.Services.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("fk_commissions_service");

                    b.HasOne("HomeServicePlatform.Domain.Modules.Tasker.Entities.TaskerProfile", "TaskerProfile")
                        .WithMany()
                        .HasForeignKey("TaskerId")
                        .HasConstraintName("fk_commissions_tasker");

                    b.Navigation("Service");

                    b.Navigation("TaskerProfile");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Operations.Entities.Dispute", b =>
                {
                    b.HasOne("HomeServicePlatform.Domain.Modules.Bookings.Entities.Booking", "Booking")
                        .WithMany("Disputes")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_disputes_booking");

                    b.HasOne("HomeServicePlatform.Domain.Modules.Identity.Entities.User", "RaisedBy")
                        .WithMany()
                        .HasForeignKey("RaisedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_disputes_raised_by");

                    b.Navigation("Booking");

                    b.Navigation("RaisedBy");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Operations.Entities.Message", b =>
                {
                    b.HasOne("HomeServicePlatform.Domain.Modules.Bookings.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_booking");

                    b.HasOne("HomeServicePlatform.Domain.Modules.Identity.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_sender");

                    b.Navigation("Booking");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Operations.Entities.Notification", b =>
                {
                    b.HasOne("HomeServicePlatform.Domain.Modules.Identity.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Operations.Entities.Review", b =>
                {
                    b.HasOne("HomeServicePlatform.Domain.Modules.Bookings.Entities.BookingItem", "BookingItem")
                        .WithOne()
                        .HasForeignKey("HomeServicePlatform.Domain.Modules.Operations.Entities.Review", "BookingItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_booking_item");

                    b.HasOne("HomeServicePlatform.Domain.Modules.Identity.Entities.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_customer");

                    b.HasOne("HomeServicePlatform.Domain.Modules.Tasker.Entities.TaskerProfile", "TaskerProfile")
                        .WithMany()
                        .HasForeignKey("TaskerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_tasker_profile");

                    b.Navigation("BookingItem");

                    b.Navigation("Customer");

                    b.Navigation("TaskerProfile");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Payments.Entities.Payment", b =>
                {
                    b.HasOne("HomeServicePlatform.Domain.Modules.Bookings.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_booking");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Payments.Entities.Refund", b =>
                {
                    b.HasOne("HomeServicePlatform.Domain.Modules.Payments.Entities.Payment", "Payment")
                        .WithMany("Refunds")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refunds_payment");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Payments.Entities.Wallet", b =>
                {
                    b.HasOne("HomeServicePlatform.Domain.Modules.Identity.Entities.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("HomeServicePlatform.Domain.Modules.Payments.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wallets_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Payments.Entities.WalletTransaction", b =>
                {
                    b.HasOne("HomeServicePlatform.Domain.Modules.Payments.Entities.Wallet", "Wallet")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wallet_transactions_wallet");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Services.Entities.Service", b =>
                {
                    b.HasOne("HomeServicePlatform.Domain.Modules.Services.Entities.Category", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_services_category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Tasker.Entities.TaskerProfile", b =>
                {
                    b.HasOne("HomeServicePlatform.Domain.Modules.Identity.Entities.User", "User")
                        .WithOne("TaskerProfile")
                        .HasForeignKey("HomeServicePlatform.Domain.Modules.Tasker.Entities.TaskerProfile", "TaskerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasker_profile_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Tasker.Entities.TaskerSchedule", b =>
                {
                    b.HasOne("HomeServicePlatform.Domain.Modules.Tasker.Entities.TaskerProfile", "TaskerProfile")
                        .WithMany("TaskerSchedules")
                        .HasForeignKey("TaskerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasker_schedules_tasker_profile");

                    b.Navigation("TaskerProfile");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Tasker.Entities.TaskerService", b =>
                {
                    b.HasOne("HomeServicePlatform.Domain.Modules.Services.Entities.Service", "Service")
                        .WithMany("TaskerServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasker_services_service");

                    b.HasOne("HomeServicePlatform.Domain.Modules.Tasker.Entities.TaskerProfile", "TaskerProfile")
                        .WithMany("TaskerServices")
                        .HasForeignKey("TaskerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasker_services_tasker_profile");

                    b.Navigation("Service");

                    b.Navigation("TaskerProfile");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Tasker.Entities.TaskerServicePrice", b =>
                {
                    b.HasOne("HomeServicePlatform.Domain.Modules.Services.Entities.Service", "Service")
                        .WithMany("TaskerServicePrices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_prices_service");

                    b.HasOne("HomeServicePlatform.Domain.Modules.Tasker.Entities.TaskerProfile", "TaskerProfile")
                        .WithMany("TaskerServicePrices")
                        .HasForeignKey("TaskerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_prices_tasker");

                    b.Navigation("Service");

                    b.Navigation("TaskerProfile");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Tasker.Entities.TaskerTimeOff", b =>
                {
                    b.HasOne("HomeServicePlatform.Domain.Modules.Tasker.Entities.TaskerProfile", "TaskerProfile")
                        .WithMany("TaskerTimeOffs")
                        .HasForeignKey("TaskerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasker_time_offs_tasker_profile");

                    b.Navigation("TaskerProfile");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Bookings.Entities.Booking", b =>
                {
                    b.Navigation("BookingAddress");

                    b.Navigation("BookingHistories");

                    b.Navigation("BookingItems");

                    b.Navigation("Disputes");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Identity.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Identity.Entities.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("TaskerProfile");

                    b.Navigation("UserRoles");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Payments.Entities.Payment", b =>
                {
                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Payments.Entities.Wallet", b =>
                {
                    b.Navigation("WalletTransactions");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Services.Entities.Category", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Services.Entities.Service", b =>
                {
                    b.Navigation("BookingItems");

                    b.Navigation("TaskerServicePrices");

                    b.Navigation("TaskerServices");
                });

            modelBuilder.Entity("HomeServicePlatform.Domain.Modules.Tasker.Entities.TaskerProfile", b =>
                {
                    b.Navigation("TaskerSchedules");

                    b.Navigation("TaskerServicePrices");

                    b.Navigation("TaskerServices");

                    b.Navigation("TaskerTimeOffs");
                });
#pragma warning restore 612, 618
        }
    }
}
