using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HomeServicePlatform.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class FixIdentitySequencesAfterSystemSeed : Migration
    {
        // Các tài khoản/ví hệ thống được seed với id cố định 9_000_000_001/2 (xem SystemAccounts).
        // Vì user_id/wallet_id là cột identity (GENERATED BY DEFAULT AS IDENTITY), việc chèn giá trị
        // explicit KHÔNG tự đẩy sequence; nếu sequence bị đồng bộ theo MAX(id) nó sẽ dính mốc 9 tỷ,
        // khiến mọi id sinh mới sau đó nhảy vọt lên 9 tỷ. Migration này kéo sequence về đúng mốc của
        // dữ liệu THẬT (bỏ qua các dòng hệ thống >= 9_000_000_000) để id mới lại nhỏ gọn.
        private const long SystemAccountFloor = 9_000_000_000L;

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            ResyncSequence(migrationBuilder, table: "users", column: "user_id");
            ResyncSequence(migrationBuilder, table: "wallets", column: "wallet_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Không rollback: setval chỉ điều chỉnh con trỏ sinh id, không đổi dữ liệu.
        }

        private static void ResyncSequence(MigrationBuilder migrationBuilder, string table, string column)
        {
            // - Nếu đã có dữ liệu thật: setval(seq, MAX_thật, true)  -> id kế tiếp = MAX_thật + 1
            // - Nếu chưa có dữ liệu thật: setval(seq, 1, false)      -> id kế tiếp = 1
            migrationBuilder.Sql($@"
SELECT setval(
    pg_get_serial_sequence('{table}', '{column}'),
    GREATEST(COALESCE((SELECT MAX({column}) FROM {table} WHERE {column} < {SystemAccountFloor}), 0), 1),
    COALESCE((SELECT MAX({column}) FROM {table} WHERE {column} < {SystemAccountFloor}), 0) > 0
);");
        }
    }
}
